apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor
  template:
    metadata:
      labels:
        app: tutor
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git:v2.32.0
          args:
            - clone
            - {{ .Values.gitRepo }}
            - /training
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: training
              mountPath: /training
      containers:
        - name: backend
          image: ueber/tutor-backend:0.0.1
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: TRAINING_DIR
              value: "/training"
            - name: TRAINING_FILE
              value: "{{ .Values.trainingFile }}"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
          volumeMounts:
            - name: training
              mountPath: /training
            - name: kubeconfig
              mountPath: /root/.kube
        - name: ide
          image: ueber/tutor-ide:0.0.1
          imagePullPolicy: Always
          ports:
            - name: ide
              containerPort: 3000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
              # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8080
          volumeMounts:
            - name: training
              mountPath: /training
            - name: kubeconfig
              mountPath: /root/.kube
        - name: frontend
          image: ueber/tutor-frontend:0.0.1
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80
          env:
            - name: API_URL
              value: "{{ .Values.protocol }}://{{ .Values.host }}:{{ .Values.backend.nodePort }}"
            - name: IDE_URL
              value: "{{ .Values.protocol }}://{{ .Values.host }}:{{ .Values.ide.nodePort }}"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
              # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8080
      volumes:
        - name: training
        # TODO
          # persistentVolumeClaim:
          #   claimName: tutor
          emptyDir: {}
        - name: kubeconfig
          secret:
            secretName: kubeconfig
            