# TODO in the end only fe has to be exposed via ingress

apiVersion: v1
kind: Service
metadata:
  name: tutor
spec:
  type: NodePort
  selector:
    app: tutor
  ports:
  # TODO in prod backend and ide do not need to get exposed due to everyting is running on localhost
    - name: backend
      port: 8080
      targetPort: backend
      nodePort: {{ .Values.backend.nodePort }}
    - name: ide
      port: 8081
      targetPort: ide
      nodePort: {{ .Values.ide.nodePort }}
    - name: frontend
      port: 80
      targetPort: frontend
      nodePort: {{ .Values.frontend.nodePort }}















