# TODO in the end only fe has to be exposed via ingress

apiVersion: v1
kind: Service
metadata:
  namespace: tutor
  name: tutor
spec:
  type: NodePort
  selector:
    app: tutor
  ports:
    - name: backend
      port: 8080
      targetPort: backend
      nodePort: 30100
    - name: ide
      port: 8081
      targetPort: ide
      nodePort: 30101















