apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tutor
  name: tutor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor
  template:
    metadata:
      labels:
        app: tutor
    spec:
      initContainers:
        - name: git-cloner
          image: alpine/git:v2.32.0
          args:
            - clone
            - https://github.com/stroebitzer/tutor-training.git
            - /training
          # TODO liveness readiness & resources
          volumeMounts:
            - name: training
              mountPath: /training
      containers:
        - name: backend
          image: ueber/tutor-backend:0.0.1
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1000Mi
          env:
            - name: TRAINING_DIR
              value: "/training"
            - name: TRAINING_FILE
              value: ".training.yaml"
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
          volumeMounts:
            - name: training
              mountPath: /training
        - name: ide
          image: ueber/tutor-ide:0.0.1
          imagePullPolicy: Always
          ports:
            - name: ide
              containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1000Mi
              # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8080
          volumeMounts:
            - name: training
              mountPath: /home/project
        - name: frontend
          image: ueber/tutor-frontend:0.0.1
          imagePullPolicy: Always
          ports:
            - name: frontend
              containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1000Mi
              # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8080
      volumes:
        - name: training
        # TODO
          # persistentVolumeClaim:
          #   claimName: tutor
          emptyDir: {}
            